// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn36SmxD9hEhh3vvVqCpvSfBB9rVVNcVE',
    appId: '1:650764290946:web:7d95e08b5a71e5abdf5d9b',
    messagingSenderId: '650764290946',
    projectId: 'todolist2-27592',
    authDomain: 'todolist2-27592.firebaseapp.com',
    storageBucket: 'todolist2-27592.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyuXNidxAQVtrtlRdV-RI4XhfTnpwpCUs',
    appId: '1:650764290946:android:9dffe13254fa03b8df5d9b',
    messagingSenderId: '650764290946',
    projectId: 'todolist2-27592',
    storageBucket: 'todolist2-27592.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHqqpSg0KjVxeTkjC6KuU2UT3MqXIwCTA',
    appId: '1:650764290946:ios:008b522841814b1adf5d9b',
    messagingSenderId: '650764290946',
    projectId: 'todolist2-27592',
    storageBucket: 'todolist2-27592.appspot.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHqqpSg0KjVxeTkjC6KuU2UT3MqXIwCTA',
    appId: '1:650764290946:ios:008b522841814b1adf5d9b',
    messagingSenderId: '650764290946',
    projectId: 'todolist2-27592',
    storageBucket: 'todolist2-27592.appspot.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn36SmxD9hEhh3vvVqCpvSfBB9rVVNcVE',
    appId: '1:650764290946:web:e3ce0e47c42fccecdf5d9b',
    messagingSenderId: '650764290946',
    projectId: 'todolist2-27592',
    authDomain: 'todolist2-27592.firebaseapp.com',
    storageBucket: 'todolist2-27592.appspot.com',
  );
}
