// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPrb0zyPjGrelTPY-k9PT0CaPti7tylkk',
    appId: '1:1059219864369:web:be6169e2b233ee600d4e10',
    messagingSenderId: '1059219864369',
    projectId: 'todonew-15838',
    authDomain: 'todonew-15838.firebaseapp.com',
    storageBucket: 'todonew-15838.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCflRdTbbi23GdDeCmgCmXJNFgFlkGO_p4',
    appId: '1:1059219864369:android:7a9dac483674a60c0d4e10',
    messagingSenderId: '1059219864369',
    projectId: 'todonew-15838',
    storageBucket: 'todonew-15838.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFP4sh6YCSajthjQbDPPM1NjKlUTnUMsU',
    appId: '1:1059219864369:ios:37acb55a4544853d0d4e10',
    messagingSenderId: '1059219864369',
    projectId: 'todonew-15838',
    storageBucket: 'todonew-15838.appspot.com',
    iosBundleId: 'com.example.todoLog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFP4sh6YCSajthjQbDPPM1NjKlUTnUMsU',
    appId: '1:1059219864369:ios:37acb55a4544853d0d4e10',
    messagingSenderId: '1059219864369',
    projectId: 'todonew-15838',
    storageBucket: 'todonew-15838.appspot.com',
    iosBundleId: 'com.example.todoLog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPrb0zyPjGrelTPY-k9PT0CaPti7tylkk',
    appId: '1:1059219864369:web:e46df9ab5cde330a0d4e10',
    messagingSenderId: '1059219864369',
    projectId: 'todonew-15838',
    authDomain: 'todonew-15838.firebaseapp.com',
    storageBucket: 'todonew-15838.appspot.com',
  );

}